// <auto-generated />
using HangmanAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HangmanAPI.Migrations
{
    [DbContext(typeof(WordDBContext))]
    [Migration("20230726223536_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("HangmanAPI.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Difficulty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = "hard",
                            Name = "abruptly"
                        },
                        new
                        {
                            Id = 2,
                            Difficulty = "standard",
                            Name = "guest"
                        },
                        new
                        {
                            Id = 3,
                            Difficulty = "hard",
                            Name = "crypt"
                        },
                        new
                        {
                            Id = 4,
                            Difficulty = "standard",
                            Name = "backpack"
                        },
                        new
                        {
                            Id = 5,
                            Difficulty = "hard",
                            Name = "schnapps"
                        },
                        new
                        {
                            Id = 6,
                            Difficulty = "standard",
                            Name = "phone"
                        },
                        new
                        {
                            Id = 7,
                            Difficulty = "standard",
                            Name = "moon"
                        },
                        new
                        {
                            Id = 8,
                            Difficulty = "hard",
                            Name = "twelfth"
                        },
                        new
                        {
                            Id = 9,
                            Difficulty = "hard",
                            Name = "haiku"
                        },
                        new
                        {
                            Id = 10,
                            Difficulty = "standard",
                            Name = "dog"
                        },
                        new
                        {
                            Id = 11,
                            Difficulty = "hard",
                            Name = "psyche"
                        },
                        new
                        {
                            Id = 12,
                            Difficulty = "hard",
                            Name = "kiosk"
                        },
                        new
                        {
                            Id = 13,
                            Difficulty = "standard",
                            Name = "clock"
                        },
                        new
                        {
                            Id = 14,
                            Difficulty = "standard",
                            Name = "elephant"
                        },
                        new
                        {
                            Id = 15,
                            Difficulty = "standard",
                            Name = "basketball"
                        },
                        new
                        {
                            Id = 16,
                            Difficulty = "hard",
                            Name = "buffalo"
                        },
                        new
                        {
                            Id = 17,
                            Difficulty = "hard",
                            Name = "journal"
                        },
                        new
                        {
                            Id = 18,
                            Difficulty = "hard",
                            Name = "espionage"
                        },
                        new
                        {
                            Id = 19,
                            Difficulty = "hard",
                            Name = "carbohydrate"
                        },
                        new
                        {
                            Id = 20,
                            Difficulty = "standard",
                            Name = "crate"
                        },
                        new
                        {
                            Id = 21,
                            Difficulty = "standard",
                            Name = "earth"
                        },
                        new
                        {
                            Id = 22,
                            Difficulty = "standard",
                            Name = "float"
                        },
                        new
                        {
                            Id = 23,
                            Difficulty = "hard",
                            Name = "unknown"
                        },
                        new
                        {
                            Id = 24,
                            Difficulty = "standard",
                            Name = "luxury"
                        },
                        new
                        {
                            Id = 25,
                            Difficulty = "standard",
                            Name = "banjo"
                        },
                        new
                        {
                            Id = 26,
                            Difficulty = "hard",
                            Name = "buzzard"
                        },
                        new
                        {
                            Id = 27,
                            Difficulty = "hard",
                            Name = "rooster"
                        },
                        new
                        {
                            Id = 28,
                            Difficulty = "standard",
                            Name = "shovel"
                        },
                        new
                        {
                            Id = 29,
                            Difficulty = "hard",
                            Name = "zombie"
                        },
                        new
                        {
                            Id = 30,
                            Difficulty = "hard",
                            Name = "bayou"
                        },
                        new
                        {
                            Id = 31,
                            Difficulty = "hard",
                            Name = "jackpot"
                        },
                        new
                        {
                            Id = 32,
                            Difficulty = "hard",
                            Name = "cobweb"
                        },
                        new
                        {
                            Id = 33,
                            Difficulty = "hard",
                            Name = "vortex"
                        },
                        new
                        {
                            Id = 34,
                            Difficulty = "hard",
                            Name = "glyph"
                        },
                        new
                        {
                            Id = 35,
                            Difficulty = "hard",
                            Name = "jaundice"
                        },
                        new
                        {
                            Id = 36,
                            Difficulty = "hard",
                            Name = "swivel"
                        },
                        new
                        {
                            Id = 37,
                            Difficulty = "hard",
                            Name = "syndrome"
                        },
                        new
                        {
                            Id = 38,
                            Difficulty = "hard",
                            Name = "transcript"
                        },
                        new
                        {
                            Id = 39,
                            Difficulty = "standard",
                            Name = "medicine"
                        },
                        new
                        {
                            Id = 40,
                            Difficulty = "hard",
                            Name = "kazoo"
                        },
                        new
                        {
                            Id = 41,
                            Difficulty = "hard",
                            Name = "whiskey"
                        },
                        new
                        {
                            Id = 42,
                            Difficulty = "standard",
                            Name = "someone"
                        },
                        new
                        {
                            Id = 43,
                            Difficulty = "hard",
                            Name = "xylophone"
                        },
                        new
                        {
                            Id = 44,
                            Difficulty = "hard",
                            Name = "zilch"
                        },
                        new
                        {
                            Id = 45,
                            Difficulty = "standard",
                            Name = "hotel"
                        },
                        new
                        {
                            Id = 46,
                            Difficulty = "standard",
                            Name = "lemon"
                        },
                        new
                        {
                            Id = 47,
                            Difficulty = "standard",
                            Name = "attention"
                        },
                        new
                        {
                            Id = 48,
                            Difficulty = "standard",
                            Name = "beautiful"
                        },
                        new
                        {
                            Id = 49,
                            Difficulty = "hard",
                            Name = "campaign"
                        },
                        new
                        {
                            Id = 50,
                            Difficulty = "standard",
                            Name = "employee"
                        },
                        new
                        {
                            Id = 51,
                            Difficulty = "standard",
                            Name = "example"
                        },
                        new
                        {
                            Id = 52,
                            Difficulty = "standard",
                            Name = "guess"
                        },
                        new
                        {
                            Id = 53,
                            Difficulty = "standard",
                            Name = "imagine"
                        },
                        new
                        {
                            Id = 54,
                            Difficulty = "standard",
                            Name = "lawyer"
                        },
                        new
                        {
                            Id = 55,
                            Difficulty = "standard",
                            Name = "manager"
                        },
                        new
                        {
                            Id = 56,
                            Difficulty = "standard",
                            Name = "market"
                        },
                        new
                        {
                            Id = 57,
                            Difficulty = "standard",
                            Name = "tasty"
                        },
                        new
                        {
                            Id = 58,
                            Difficulty = "hard",
                            Name = "juicy"
                        },
                        new
                        {
                            Id = 59,
                            Difficulty = "hard",
                            Name = "pneumonia"
                        },
                        new
                        {
                            Id = 60,
                            Difficulty = "hard",
                            Name = "vaporize"
                        },
                        new
                        {
                            Id = 61,
                            Difficulty = "standard",
                            Name = "quota"
                        },
                        new
                        {
                            Id = 62,
                            Difficulty = "standard",
                            Name = "bicycle"
                        },
                        new
                        {
                            Id = 63,
                            Difficulty = "standard",
                            Name = "notebook"
                        },
                        new
                        {
                            Id = 64,
                            Difficulty = "standard",
                            Name = "hamburger"
                        },
                        new
                        {
                            Id = 65,
                            Difficulty = "standard",
                            Name = "headphones"
                        },
                        new
                        {
                            Id = 66,
                            Difficulty = "standard",
                            Name = "computer"
                        },
                        new
                        {
                            Id = 67,
                            Difficulty = "hard",
                            Name = "ivory"
                        },
                        new
                        {
                            Id = 68,
                            Difficulty = "hard",
                            Name = "wimpy"
                        },
                        new
                        {
                            Id = 69,
                            Difficulty = "standard",
                            Name = "nice"
                        },
                        new
                        {
                            Id = 70,
                            Difficulty = "hard",
                            Name = "zodiac"
                        },
                        new
                        {
                            Id = 71,
                            Difficulty = "hard",
                            Name = "oxygen"
                        },
                        new
                        {
                            Id = 72,
                            Difficulty = "standard",
                            Name = "boredom"
                        },
                        new
                        {
                            Id = 73,
                            Difficulty = "standard",
                            Name = "mission"
                        },
                        new
                        {
                            Id = 74,
                            Difficulty = "standard",
                            Name = "morning"
                        },
                        new
                        {
                            Id = 75,
                            Difficulty = "standard",
                            Name = "newspaper"
                        },
                        new
                        {
                            Id = 76,
                            Difficulty = "standard",
                            Name = "nothing"
                        },
                        new
                        {
                            Id = 77,
                            Difficulty = "standard",
                            Name = "office"
                        },
                        new
                        {
                            Id = 78,
                            Difficulty = "standard",
                            Name = "operation"
                        },
                        new
                        {
                            Id = 79,
                            Difficulty = "hard",
                            Name = "population"
                        },
                        new
                        {
                            Id = 80,
                            Difficulty = "hard",
                            Name = "professional"
                        },
                        new
                        {
                            Id = 81,
                            Difficulty = "standard",
                            Name = "goat"
                        },
                        new
                        {
                            Id = 82,
                            Difficulty = "standard",
                            Name = "fish"
                        },
                        new
                        {
                            Id = 83,
                            Difficulty = "standard",
                            Name = "anger"
                        },
                        new
                        {
                            Id = 84,
                            Difficulty = "hard",
                            Name = "mnemonic"
                        },
                        new
                        {
                            Id = 85,
                            Difficulty = "hard",
                            Name = "matrix"
                        },
                        new
                        {
                            Id = 86,
                            Difficulty = "hard",
                            Name = "thrifty"
                        },
                        new
                        {
                            Id = 87,
                            Difficulty = "hard",
                            Name = "bandwagon"
                        },
                        new
                        {
                            Id = 88,
                            Difficulty = "hard",
                            Name = "groggy"
                        },
                        new
                        {
                            Id = 89,
                            Difficulty = "standard",
                            Name = "thought"
                        },
                        new
                        {
                            Id = 90,
                            Difficulty = "standard",
                            Name = "together"
                        },
                        new
                        {
                            Id = 91,
                            Difficulty = "standard",
                            Name = "variety"
                        },
                        new
                        {
                            Id = 92,
                            Difficulty = "hard",
                            Name = "tough"
                        },
                        new
                        {
                            Id = 93,
                            Difficulty = "hard",
                            Name = "thorough"
                        },
                        new
                        {
                            Id = 94,
                            Difficulty = "standard",
                            Name = "treat"
                        },
                        new
                        {
                            Id = 95,
                            Difficulty = "hard",
                            Name = "traditional"
                        },
                        new
                        {
                            Id = 96,
                            Difficulty = "standard",
                            Name = "theory"
                        },
                        new
                        {
                            Id = 97,
                            Difficulty = "standard",
                            Name = "denim"
                        },
                        new
                        {
                            Id = 98,
                            Difficulty = "standard",
                            Name = "cedar"
                        },
                        new
                        {
                            Id = 99,
                            Difficulty = "standard",
                            Name = "pause"
                        },
                        new
                        {
                            Id = 100,
                            Difficulty = "hard",
                            Name = "jazz"
                        },
                        new
                        {
                            Id = 101,
                            Difficulty = "hard",
                            Name = "abacus"
                        },
                        new
                        {
                            Id = 102,
                            Difficulty = "hard",
                            Name = "marshmallow"
                        },
                        new
                        {
                            Id = 103,
                            Difficulty = "standard",
                            Name = "tumbleweed"
                        },
                        new
                        {
                            Id = 104,
                            Difficulty = "hard",
                            Name = "conundrum"
                        },
                        new
                        {
                            Id = 105,
                            Difficulty = "hard",
                            Name = "diagnosis"
                        },
                        new
                        {
                            Id = 106,
                            Difficulty = "hard",
                            Name = "cryptic"
                        },
                        new
                        {
                            Id = 107,
                            Difficulty = "standard",
                            Name = "picture"
                        },
                        new
                        {
                            Id = 108,
                            Difficulty = "standard",
                            Name = "sketch"
                        },
                        new
                        {
                            Id = 109,
                            Difficulty = "standard",
                            Name = "sandwich"
                        },
                        new
                        {
                            Id = 110,
                            Difficulty = "standard",
                            Name = "fruit"
                        },
                        new
                        {
                            Id = 111,
                            Difficulty = "standard",
                            Name = "clothes"
                        },
                        new
                        {
                            Id = 112,
                            Difficulty = "standard",
                            Name = "envelope"
                        },
                        new
                        {
                            Id = 113,
                            Difficulty = "standard",
                            Name = "magic"
                        },
                        new
                        {
                            Id = 114,
                            Difficulty = "standard",
                            Name = "cube"
                        },
                        new
                        {
                            Id = 115,
                            Difficulty = "standard",
                            Name = "sofa"
                        },
                        new
                        {
                            Id = 116,
                            Difficulty = "standard",
                            Name = "hawk"
                        },
                        new
                        {
                            Id = 117,
                            Difficulty = "standard",
                            Name = "tourist"
                        },
                        new
                        {
                            Id = 118,
                            Difficulty = "standard",
                            Name = "judge"
                        },
                        new
                        {
                            Id = 119,
                            Difficulty = "hard",
                            Name = "insomnia"
                        },
                        new
                        {
                            Id = 120,
                            Difficulty = "hard",
                            Name = "audition"
                        },
                        new
                        {
                            Id = 121,
                            Difficulty = "hard",
                            Name = "scarlet"
                        },
                        new
                        {
                            Id = 122,
                            Difficulty = "hard",
                            Name = "brewery"
                        },
                        new
                        {
                            Id = 123,
                            Difficulty = "hard",
                            Name = "stigma"
                        },
                        new
                        {
                            Id = 124,
                            Difficulty = "hard",
                            Name = "junction"
                        },
                        new
                        {
                            Id = 125,
                            Difficulty = "hard",
                            Name = "stingray"
                        },
                        new
                        {
                            Id = 126,
                            Difficulty = "hard",
                            Name = "rogue"
                        },
                        new
                        {
                            Id = 127,
                            Difficulty = "hard",
                            Name = "liquor"
                        },
                        new
                        {
                            Id = 128,
                            Difficulty = "hard",
                            Name = "cosmetics"
                        },
                        new
                        {
                            Id = 129,
                            Difficulty = "hard",
                            Name = "hibiscus"
                        },
                        new
                        {
                            Id = 130,
                            Difficulty = "hard",
                            Name = "epitome"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
